### PR TITLE
send a single mail

### PR DESCRIPTION
**Pull request by Holmeron**
send a single mail when the timeout is greater than the time between events.

Right now, when multiple events fire inside a same 'timeout loop' it sends an email for each event. 
I believe your intent is to concatenate all of those events in a single mail, to prevent too much spam.

### CODE REVIEW

**Comment by dcyou** [comment]
+1 it will be very appreciate to merge this PR

**Comment by soyuka** [comment]
Oh yeah nice catch! Sorry I don't really use this but rather a modified version where I think I fixed this. Thanks!

**Comment by soyuka** [comment]
Are you guys using this through npm? (ie should I bump the version?)

**Comment by soyuka** [comment]
Ok, nvm patched in 1.0.2

**Pull request merged**
